name: maharshi's blog
title: null
description: some of my blogs go here
domain: maharshi-pandya.github.io
url: https://maharshi-pandya.github.io
baseurl: /blogs/
author:
  name: maharshi pandya
  email: maharshi.pandya2002@gmail.com
