exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"

name: maharshi's blog
title: null
description: some of my blogs go here
domain: maharshi-pandya.github.io
url: https://maharshi-pandya.github.io
baseurl: /blog/
author:
  name: maharshi pandya
  email: maharshi.pandya2002@gmail.com
